require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InteractionsController do

  # This should return the minimal set of attributes required to create a valid
  # Interaction. As you add validations to Interaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InteractionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all interactions as @interactions" do
      interaction = Interaction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:interactions).should eq([interaction])
    end
  end

  describe "GET show" do
    it "assigns the requested interaction as @interaction" do
      interaction = Interaction.create! valid_attributes
      get :show, {:id => interaction.to_param}, valid_session
      assigns(:interaction).should eq(interaction)
    end
  end

  describe "GET new" do
    it "assigns a new interaction as @interaction" do
      get :new, {}, valid_session
      assigns(:interaction).should be_a_new(Interaction)
    end
  end

  describe "GET edit" do
    it "assigns the requested interaction as @interaction" do
      interaction = Interaction.create! valid_attributes
      get :edit, {:id => interaction.to_param}, valid_session
      assigns(:interaction).should eq(interaction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Interaction" do
        expect {
          post :create, {:interaction => valid_attributes}, valid_session
        }.to change(Interaction, :count).by(1)
      end

      it "assigns a newly created interaction as @interaction" do
        post :create, {:interaction => valid_attributes}, valid_session
        assigns(:interaction).should be_a(Interaction)
        assigns(:interaction).should be_persisted
      end

      it "redirects to the created interaction" do
        post :create, {:interaction => valid_attributes}, valid_session
        response.should redirect_to(Interaction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved interaction as @interaction" do
        # Trigger the behavior that occurs when invalid params are submitted
        Interaction.any_instance.stub(:save).and_return(false)
        post :create, {:interaction => {  }}, valid_session
        assigns(:interaction).should be_a_new(Interaction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Interaction.any_instance.stub(:save).and_return(false)
        post :create, {:interaction => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested interaction" do
        interaction = Interaction.create! valid_attributes
        # Assuming there are no other interactions in the database, this
        # specifies that the Interaction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Interaction.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => interaction.to_param, :interaction => { "these" => "params" }}, valid_session
      end

      it "assigns the requested interaction as @interaction" do
        interaction = Interaction.create! valid_attributes
        put :update, {:id => interaction.to_param, :interaction => valid_attributes}, valid_session
        assigns(:interaction).should eq(interaction)
      end

      it "redirects to the interaction" do
        interaction = Interaction.create! valid_attributes
        put :update, {:id => interaction.to_param, :interaction => valid_attributes}, valid_session
        response.should redirect_to(interaction)
      end
    end

    describe "with invalid params" do
      it "assigns the interaction as @interaction" do
        interaction = Interaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Interaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => interaction.to_param, :interaction => {  }}, valid_session
        assigns(:interaction).should eq(interaction)
      end

      it "re-renders the 'edit' template" do
        interaction = Interaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Interaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => interaction.to_param, :interaction => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested interaction" do
      interaction = Interaction.create! valid_attributes
      expect {
        delete :destroy, {:id => interaction.to_param}, valid_session
      }.to change(Interaction, :count).by(-1)
    end

    it "redirects to the interactions list" do
      interaction = Interaction.create! valid_attributes
      delete :destroy, {:id => interaction.to_param}, valid_session
      response.should redirect_to(interactions_url)
    end
  end

end
